name: Deploy Changes

on:
  # Trigger manually if needed
  workflow_dispatch:

  # Trigger when PR is closed/merged
  pull_request:
    types: [closed]

env:
  # CS Tools version to install
  CS_TOOLS_VERSION: v1.5.13b1

  # Auth values from GitHub secrets (same ones you use for fetch & commit)
  CS_TOOLS_THOUGHTSPOT__URL: ${{ secrets.PRD_THOUGHTSPOT_URL }}
  CS_TOOLS_THOUGHTSPOT__USERNAME: ${{ secrets.PRD_THOUGHTSPOT_USERNAME }}
  CS_TOOLS_THOUGHTSPOT__SECRET_KEY: ${{ secrets.PRD_THOUGHTSPOT_SECRET_KEY }}

  # ThoughtSpot environment details
  TS_ENV_NAME: ts-prod
  TS_DESTINATION_ORG_ID: 1911636566

jobs:
  run_deploy_api:
    if: github.event.pull_request.merged && github.event.pull_request.base.ref == 'ts-prod'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the ts-prod branch
        uses: actions/checkout@v4
        with:
          ref: ts-prod

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install CS Tools
        run: pip install "cs_tools[cli] @ https://github.com/thoughtspot/cs_tools/archive/${{ env.CS_TOOLS_VERSION }}.zip"

      - name: Deploy to ThoughtSpot
        run: cs_tools tools git branches deploy --branch-name ts-prod --org 1911636566 --config ENV:
